### ISSUE TITLE
Bad responsive sizes

### ISSUE THREAD

**Issue by harundogdu** [ahmetenesbahar/drawing-app#8]
Screen support is required for laptops and tablets.

<img width="1495" alt="Ekran Resmi 2022-11-03 22 30 27" src="https://user-images.githubusercontent.com/43449361/199816669-bf585260-894c-432d-869a-d8f0ab10b47d.png">

**Comment by ahmetenesbahar** [comment]
This app is not for mobile phones / tablets  but i will consider this issue sometime. Thanks for help :)
